name: CommonTask

on:
  push:
    branches:
      - feature/**
      - develop/**
    paths:
      - backend/**
      - cli/**
      - dotNet/**

jobs:
  SetUp:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install java 11 (Temurin)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'